
#include "HttpConnectionHandler.hpp"

        HttpConnectionHandler::HttpConnectionHandler(Socket& client){
            const char* const SERVER_NAME = "ToBeNamed";
            std::ostringstream message;
            message << "<!DOCTYPE html><html lang=\"en\"><meta charset=\"ascii\"/>";
            message << "<title>Hi!</title><h1>Welcome!</h1>";
            message << "<hr><p>Generated by " << SERVER_NAME << "</p></html>";
            // Status line
            client << "HTTP/1.0 200 0K\r\n";
            // Response header
            client << "Server: " << SERVER_NAME << "\r\n";
            client << "Content-Type: text/html; charset=ascii\r\n";
            client << "Content-Length: " << message.str().length() << "\r\n";
            client << "\r\n";
            // Body
            client << message.str();
            client.send();
            // char* leak = new char[message.str().length() + 1]; *leak = 0;
        }
        void HttpConnectionHandler::StartConnection(){

        }
        void HttpConnectionHandler::handleHttpRequest(HttpRequest request, HttpResponse response){

        }
        int HttpConnectionHandler::run(){
            HttpRequest *request = new HttpRequest();
            HttpResponse *response = new HttpResponse();
            return 0;
        }